version: '3'
services:
  ollama:
    image: ollama/ollama:rocm
    container_name: ollama
    privileged: true
    restart: always
    ports:
      - "${OLLAMA_PORT:-11434}:11434"
    volumes:
      - ./ollama_data:/root/.ollama
    group_add:
      - "992"
      - "video"
    devices:
      - "/dev/kfd"
      - "/dev/dri"
    environment:
      - HSA_OVERRIDE_GFX_VERSION=10.3.0
      - HSA_ENABLE_SDMA=1
      - OLLAMA_FLASH_ATTENTION=1
      - OLLAMA_KV_CACHE_TYPE=q8_0
      - OLLAMA_MAX_INPUT_TOKENS=131072
      - OLLAMA_CONTEXT_LENGTH=131072
      - OLLAMA_KEEP_ALIVE=-1
      - ROCM_PATH=/opt/rocm
      - ROCR_VISIBLE_DEVICES=all
      - GPU_MAX_HEAP_SIZE=100
      - GPU_SINGLE_ALLOC_PERCENT=100
      
  open-webui:
    image: ${WEBUI_IMAGE:-ghcr.io/open-webui/open-webui:main}
    container_name: open-webui
    restart: always
    volumes:
      - ./webui_data:/app/backend/data
    ports:
      - "${WEBUI_PORT:-8080}:${WEBUI_PORT_INTERNAL:-8080}"
    environment:
      - OLLAMA_API_BASE_URL=http://ollama:11434
      - WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY:-change_this_to_a_secure_random_string}
      - WEBUI_AUTH=${WEBUI_AUTH:-true}
      - WEBUI_CORS=${WEBUI_CORS:-false}
      - WEBUI_HOST=${WEBUI_HOST:-0.0.0.0}
      - WEBUI_PORT=${WEBUI_PORT_INTERNAL:-8080}
      - WEBUI_DB=${WEBUI_DB:-sqlite}
      - WEBUI_ALLOW_PASSWORDLESS_USER_CREATION=${WEBUI_ALLOW_PASSWORDLESS_USER_CREATION:-false}
    depends_on:
      - ollama
